# ===============================
# DEFAULT CONFIG - BASE EXPERIMENT
# ===============================

experiment:
  seed: 42
  device: cuda
  description: "HSI brain benchmark replication"
  output_dir: outputs/default
  folds: 5
  split_strategy: patient_level  # very important: split by patient, not by pixel

data:
  root_dir: data/hsi_dataset
  processed_dir: data/processed
  raw_bands: 826
  cleaned_bands: 645
  reduced_bands: 128
  calibration: true
  smoothing:
    enabled: true
    window: 5
  remove_bands:
    start: 56
    end: 126
  downsampling:
    enabled: true
    step_nm: 3.61
    final_channels: 128
  normalization: minmax
  absorbance_conversion: true
  classes: [TT, NT, BV, BG]
  gt_map_name: gtMap
  white_ref_name: whiteReference
  dark_ref_name: darkReference
  raw_cube_name: raw

partition:
  folds: 5
  split: [0.6, 0.2, 0.2]  # train/val/test
  level: patient
  random_seed: 42

reduction:
  enabled: true
  method: kmeans
  clusters_per_class: 100
  pixels_per_centroid: [10, 20, 40]  # three experiments
  total_per_class: [1000, 2000, 4000]

model:
  name: dnn_1d
  input_channels: 128
  num_classes: 3
  activation: relu
  batch_norm: true
  dropout: 0.0
  hidden_dims: [L, L]  # optimized hyperparam
  optimizer: sgd
  learning_rate: 0.1
  epochs: 300

supervised_models: [SVM-L, SVM-RBF, KNN-E, KNN-C, RF, DNN]
unsupervised_models: [HKM]
unmixing_models: [EBEAE, NEBEAE]

spatial_spectral:
  enabled: true
  pca_components: 1
  knn_filter:
    enabled: true
    lambda: 1
    K: 40
    window_size: 8
    distance: euclidean
  hkm:
    enabled: true
    clusters: 24
  mv:
    enabled: true
    method: fusion_color_gradient

training:
  optimizer: sgd
  learning_rate: 0.1
  epochs: 300
  batch_size: 64
  weight_decay: 0.0
  loss_fn: cross_entropy
  early_stopping: false

evaluation:
  metrics: [f1_macro, oa, sensitivity, specificity]
  exclude_classes: [BG]
  average: macro
  visualize_results: true
  save_density_map: true
  report_format: csv

