# ===============================
# EXPERIMENT 1 - DNN BASELINE
# ===============================
defaults:
  - default.yaml

experiment:
  name: exp1_brain_dnn
  description: "Two-layer 1D DNN for brain tumour classification (paper baseline)"
  output_dir: outputs/exp1_brain_dnn

# --- model overrides ---
model:
  name: dnn_1d
  type: deep
  input_channels: 128         # after spectral downsampling
  num_classes: 3              # TT, NT, BV  (BG excluded in metrics)
  hidden_dims: [256, 256]     # optimized 'L' from paper
  activation: relu
  batch_norm: true
  dropout: 0.5
  optimizer: sgd
  learning_rate: 0.1
  epochs: 300
  weight_decay: 0.0

# --- data / reduction overrides ---
reduction:
  enabled: true
  method: kmeans
  clusters_per_class: 100
  pixels_per_centroid: 20      # 2000 pixels/class (n=20)
  total_per_class: 2000

partition:
  folds: 5
  split: [0.6, 0.2, 0.2]
  level: patient
  random_seed: 42

evaluation:
  metrics: [f1_macro, oa, sensitivity, specificity]
  exclude_classes: [BG]
  average: macro
  visualize_results: true
  save_density_map: true

training:
  epochs: 300
  batch_size: 64
  learning_rate: 0.1
  optimizer: sgd
  momentum: 0.9   

postprocessing:
  hkm:
    num_clusters: 20



