# ===============================
# EXPERIMENT 2 - SVM BASELINES
# ===============================
defaults:
  - default.yaml

experiment:
  name: exp2_svm
  description: "SVM (Linear and RBF) replication from the benchmark paper"
  output_dir: outputs/exp2_svm

model:
  name: svm
  type: classical
  variants:
    - kernel: linear
      C: [0.1, 1, 10]          # search range for cost parameter
    - kernel: rbf
      C: [0.1, 1, 10]
      gamma: [0.01, 0.1, 1]    # search range for RBF width
  max_iter: 10000
  library: libsvm              # same as in paper

# --- data / reduction overrides ---
reduction:
  enabled: true
  method: kmeans
  clusters_per_class: 100
  pixels_per_centroid: 20      # use same reduced training set as DNN
  total_per_class: 2000

partition:
  folds: 5
  split: [0.6, 0.2, 0.2]
  level: patient
  random_seed: 42

evaluation:
  metrics: [f1_macro, oa, sensitivity, specificity]
  exclude_classes: [BG]
  average: macro
  visualize_results: true
  save_density_map: true

