# ===============================
# EXPERIMENT 3 - RANDOM FOREST
# ===============================
defaults:
  - default.yaml

experiment:
  name: exp3_rf
  description: "Random Forest baseline replication"
  output_dir: outputs/exp3_rf

model:
  name: random_forest
  type: classical
  n_trees: [100, 200, 500]      # paper tested multiple tree counts
  criterion: gini
  max_depth: null
  random_state: 42

# --- data reduction (same as DNN/SVM) ---
reduction:
  enabled: true
  method: kmeans
  clusters_per_class: 100
  pixels_per_centroid: 20
  total_per_class: 2000

partition:
  folds: 5
  split: [0.6, 0.2, 0.2]
  level: patient
  random_seed: 42

evaluation:
  metrics: [f1_macro, oa, sensitivity, specificity]
  exclude_classes: [BG]
  average: macro
  visualize_results: true
  save_density_map: true

