# ===============================
# EXPERIMENT 4 - KNN (EUCLIDEAN & COSINE)
# ===============================
defaults:
  - default.yaml

experiment:
  name: exp4_knn
  description: "KNN classifiers with Euclidean and Cosine distances"
  output_dir: outputs/exp4_knn

model:
  name: knn
  type: classical
  variants:
    - metric: euclidean
      n_neighbors: [3, 5, 7, 9]
    - metric: cosine
      n_neighbors: [3, 5, 7, 9]
  weights: uniform

# --- data reduction ---
reduction:
  enabled: true
  method: kmeans
  clusters_per_class: 100
  pixels_per_centroid: 20
  total_per_class: 2000

partition:
  folds: 5
  split: [0.6, 0.2, 0.2]
  level: patient
  random_seed: 42

evaluation:
  metrics: [f1_macro, oa, sensitivity, specificity]
  exclude_classes: [BG]
  average: macro
  visualize_results: true
  save_density_map: true

