# ===============================
# EXPERIMENT 7 - SPATIAL-SPECTRAL FUSION (PCA + KNN + HKM + MV)
# ===============================
defaults:
  - default.yaml

experiment:
  name: exp7_spatial_mv
  description: "Full spatial-spectral pipeline (PCA + KNN filter + HKM segmentation + MV fusion)"
  output_dir: outputs/exp7_spatial_mv

spatial_spectral:
  enabled: true

  pca:
    enabled: true
    components: 1             # 1-band PCA representation as in paper

  knn_filter:
    enabled: true
    lambda: 1
    K: 40
    window_size: 8
    distance: euclidean

  hkm:
    enabled: true
    clusters: 24

  mv:
    enabled: true
    method: fusion_color_gradient
    description: "Fuses supervised and unsupervised outputs using a color gradient fusion scheme"

# --- supervised backbone used for probability maps ---
model:
  name: dnn_1d
  type: deep
  input_channels: 128
  num_classes: 3
  hidden_dims: [256, 128]
  activation: relu
  batch_norm: true
  dropout: 0.0
  optimizer: sgd
  learning_rate: 0.1
  epochs: 300

# --- same reduction / partition settings ---
reduction:
  enabled: true
  method: kmeans
  clusters_per_class: 100
  pixels_per_centroid: 20
  total_per_class: 2000

partition:
  folds: 5
  split: [0.6, 0.2, 0.2]
  level: patient
  random_seed: 42

evaluation:
  metrics: [f1_macro, oa, sensitivity, specificity]
  exclude_classes: [BG]
  average: macro
  visualize_results: true
  save_density_map: true

